### ISSUE TITLE
Hello, sir. How do you use C3Bridge/kukavarproxy compatible API to communicate between Python and KUKA

### ISSUE THREAD

**Issue by zjf15066756472** [CompsocInternational/kuka-comms#1]
Hello, sir. How do you use C3Bridge/kukavarproxy compatible API to communicate between Python and KUKA

**Comment by 456dev** [comment]
Essentially, the official kuka control server hardware needs to be running c3bridge on boot, and the robot controller and host machine are then both installed onto a restricted network: IE they are stlet up to be able to ping each other, but not the outside world
The IP address of the robot will depend on the specific network used, but the port is always 7000 without modifying the defaults

There is 1 more peice of the puzzle not including in this repo, the actual krl program that needs to be running on the robot for this to work.
I'll try and get the source and add it to the repo today, but there was a bit of trial and error setting this all up.

It is semi - similar to the built in "job" program shown by c3control, but it's worth noting that the psudocode in the root of the repo is a bit outdated iirc


Lastly there is the actual API:
This only implements 2 commands ATM, ASCII var reading, and acsiinvar writing iirc (so it should be kuka var proxy compatible, but that is completely un tested)

However, the main interaction method is you create a kuka robot, and call the async / sync methods until they are done. Moves are prevented until the current move has finished, which my never happen (because ie the operator is not holding the run button in T1/T2)


For our usecase this was built for, see https://github.com/LUComp/waste-sorter
Since it's moving with carteasean coords, mastering (making sure a certain angle has the robot in a certain physical position/knows where it is) and setting the base location (where 0,0,0 in main coordinates is), and the tool size/location (how big the tool mounted on the end of the robot is, so telling it to rotate about a point will keep the tools tip in place, not the end of the arm

I would also recommend setting up safety bounds, so if some code does the wrong thing, the robot will not move out of a safe ISH area

Any more questions, feel free to contact me
`kuka_robot_commlib [ a t ] 0456456.xyz`
